In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('Iris.csv')

In [3]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data['Species']=lb.fit_transform(data['Species'])

In [4]:
x=data.drop(columns=['Id','Species'])
y=data['Species']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=
                                               0.2,shuffle=True,random_state=42)

In [6]:
x_train.shape,y_train.shape

((120, 4), (120,))

In [7]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
lg.fit(x_train,y_train)

LogisticRegression()

In [8]:
#evaluation
y_pred=lg.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_pred,y_test)*100
ac

100.0

In [10]:
train_pred=lg.predict(x_train)

In [11]:
train=accuracy_score(train_pred,y_train)*100
train

97.5

In [12]:
lg

LogisticRegression()

In [13]:
import pickle
with open('iris_model','wb')as f:
    pickle.dump(lg,f)

In [14]:
with open('iris_model','rb')as file:
    loaded_model=pickle.load(file)

In [15]:
loaded_model.predict([x_test.iloc[3,:]])

/Users/aungsanphyo/letscode/prjt1/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [16]:
house=pd.read_csv('housing.csv')

In [17]:
house.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [18]:
house.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [19]:
house.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [20]:
house.dropna(inplace=True)

In [21]:
house.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [22]:
house.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [23]:
house['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9034
INLAND        6496
NEAR OCEAN    2628
NEAR BAY      2270
ISLAND           5
Name: count, dtype: int64

In [24]:
from sklearn.preprocessing import OrdinalEncoder
od=LabelEncoder()
house['ocean_proximity']=od.fit_transform(house[['ocean_proximity']])

/Users/aungsanphyo/letscode/prjt1/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [25]:
house.tail(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20630,-121.32,39.29,11.0,2640.0,505.0,1257.0,445.0,3.5673,112000.0,1
20631,-121.40,39.33,15.0,2655.0,493.0,1200.0,432.0,3.5179,107200.0,1
20632,-121.45,39.26,15.0,2319.0,416.0,1047.0,385.0,3.1250,115600.0,1
20633,-121.53,39.19,27.0,2080.0,412.0,1082.0,382.0,2.5495,98300.0,1
20634,-121.56,39.27,28.0,2332.0,395.0,1041.0,344.0,3.7125,116800.0,1
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,1
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,1
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,1
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,1
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,1

In [26]:
x=house.drop(columns=['median_house_value'])
y=house['median_house_value']

In [27]:
x.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,3

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,shuffle=True,random_state=42)

In [29]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [30]:
test_pred=lr.predict(x_test)
train_pred=lr.predict(x_train)

In [31]:
from sklearn.metrics import mean_absolute_error
train_error=mean_absolute_error(train_pred,y_train)*100
test_error=mean_absolute_error(test_pred,y_test)*100

In [32]:
train_error,test_error

(5063049.74365794, 5138870.018950715)

In [33]:
house.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,3

In [34]:
house.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

In [35]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
house[['housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']]=sc.fit_transform(house[['housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']])

In [36]:
house.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,0.982163,-0.803813,-0.970325,-0.973320,-0.976833,2.345163,2.128819,3
1,-122.22,37.86,-0.606210,2.042130,1.348276,0.861339,1.670373,2.332632,1.313626,3
2,-122.24,37.85,1.855769,-0.535189,-0.825561,-0.819769,-0.843427,1.782939,1.258183,3
3,-122.25,37.85,1.855769,-0.623510,-0.718768,-0.765056,-0.733562,0.932970,1.164622,3
4,-122.25,37.85,1.855769,-0.461970,-0.611974,-0.758879,-0.628930,-0.013143,1.172418,3

In [37]:
std_x=house.drop(columns=['median_house_value'])
std_y=house['median_house_value']

In [38]:
std_x_train,std_x_test,std_y_train,std_y_test=train_test_split(std_x,std_y,test_size=0.2,shuffle=True,random_state=42)

In [39]:
x_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
17727,-121.80,37.32,14.0,4412.0,924.0,2698.0,891.0,4.7027,0
2057,-119.63,36.64,33.0,1036.0,181.0,620.0,174.0,3.4107,1
6453,-118.06,34.12,25.0,3891.0,848.0,1848.0,759.0,3.6639,1
4619,-118.31,34.07,28.0,2362.0,949.0,2759.0,894.0,2.2364,0
15266,-117.27,33.04,27.0,1839.0,392.0,1302.0,404.0,3.5500,4

In [40]:
std_lr=LinearRegression()
std_lr.fit(std_x_train,std_y_train)

LinearRegression()

In [41]:
str_test_pred=std_lr.predict(std_x_test)
str_train_pred=std_lr.predict(std_x_train)
str_test_error=mean_absolute_error(str_test_pred,std_y_test)*100
str_train_error=mean_absolute_error(str_train_pred,std_y_train)*100

In [42]:
str_test_error,str_train_error

(44.5182663383965, 43.86143182090778)

In [43]:
std_lr

LinearRegression()

In [44]:
with open('house_model','wb')as f:
 pickle.dump(std_lr,f)

In [45]:
print(type(std_lr))

<class 'sklearn.linear_model._base.LinearRegression'>